# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mayfly/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mayfly)

$(call add-radio-file-sha1-checked,radio/abl.img,356f3195192ea01ae117a4c215e42ec276da6943)
$(call add-radio-file-sha1-checked,radio/aop.img,b0f9f90fe692364f3d576d39cd8d035bb91f4ec5)
$(call add-radio-file-sha1-checked,radio/aop_config.img,5dcdda1f599be4177e52845856c97699b293ac9c)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,9de00078b73fedee63d0ebdba434583139f31b49)
$(call add-radio-file-sha1-checked,radio/cpucp.img,f78a03925de8c21d78e69b939a2956c6e3595f53)
$(call add-radio-file-sha1-checked,radio/devcfg.img,c37b7fa52654941b10ebc57a4ea5b20aed3532b0)
$(call add-radio-file-sha1-checked,radio/dsp.img,259329c9822fa19d5ba7f6e06794c44ceec3d220)
$(call add-radio-file-sha1-checked,radio/featenabler.img,d4545a481b69e2a4a90304e5b363cb15ebc71215)
$(call add-radio-file-sha1-checked,radio/hyp.img,d2c2525af9a9c28cfbeffcdfadbdfc637722c52e)
$(call add-radio-file-sha1-checked,radio/imagefv.img,f48646332caef7fdd87d03d4f5c766e6e20afc9c)
$(call add-radio-file-sha1-checked,radio/keymaster.img,cae78739507156d27c74185a1aff87b9e663a42a)
$(call add-radio-file-sha1-checked,radio/modem.img,42964c4e0e0f734465e38499d190e752f9295806)
$(call add-radio-file-sha1-checked,radio/qupfw.img,a9a08e6858610f0082eedaf88938fdaa8dbe3e6c)
$(call add-radio-file-sha1-checked,radio/shrm.img,e4c5833da327a5c98c29c482b2f5e4f80e4094d3)
$(call add-radio-file-sha1-checked,radio/tz.img,955e9dd2fbf34d464ef32fb02959100a777ef586)
$(call add-radio-file-sha1-checked,radio/uefi.img,58e5de66a9dbbb4485ce14fa5cc9679eff979d07)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,0d7f04a198b229e6e8827eae7a24fdd763a0ea38)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,ba20165ced28dca887728c18dedd4135ad492976)
$(call add-radio-file-sha1-checked,radio/xbl.img,a6e55ef808e2e5e37d2744693152719fe526af0d)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,217fd57e38cb7f7b2ed86f1039ba7ca545ab31bc)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,8767b8a77d2e159729cc4e5072e449cb048ad449)

endif
